### ISSUE TITLE
Make the "warning" more visible.

### ISSUE THREAD

**Issue by rodrigograca31** [jkingsman/get-git#3]
I've noticed two things about the `#note` element.
1. The `position` is `absolute`. This makes it disappear when you scroll.... IMHO it should be: `position: fixed;`
2. Then the `z-index` is `101` ... And some sites have elements (e.g.: menus) with a bigger z-index number.... IMHO it should be: `z-index: 10001`

Do you guys agree?
Can I send a pull request with this two modifications?

**Comment by jkingsman** [comment]
totally; go for it!

**Comment by rodrigograca31** [comment]
Glad I could help! :smile:

**Comment by jkingsman** [comment]
I appreciate the contribution. I don't have much time to maintain this and its successor [Bishop](https://github.com/jkingsman/Bishop), so any PR's/tweaks/bug fixes/features will pretty much always get merged in.
