### ISSUE TITLE
Stop retesting websites...

### ISSUE THREAD

**Issue by rodrigograca31** [jkingsman/get-git#4]
Keeping a list of tested websites would probably not be feasible.
But you can at least not retest the ones that are on the "Vulnerable Sites" list....

**Comment by rodrigograca31** [comment]
Hey @jkingsman could you delete this issue? 
Apparently you already do this.... But for some reason there was one website that even after refreshing would warn me again....

**Comment by jkingsman** [comment]
No problem - you can't actually delete an issue, but you can close it.

**Comment by rodrigograca31** [comment]
Thanks! On my side I couldn't even closed it...

**Comment by jkingsman** [comment]
Oh weird.
