### ISSUE TITLE
Add an option to blacklist certain websites

### ISSUE THREAD

**Issue by gsingh93** [jkingsman/get-git#6]
The extension keeps giving me false positives on google searches, because obviously appending `/.git` to a search query is going to work.

This also makes me wonder if instead of just blindly appending `/.git`, you should first strip any URL parameters and then append `/.git`.

**Comment by jkingsman** [comment]
Hi! Thanks for the feedback. I would encourage you to switch over to [Bishop](https://github.com/jkingsman/Bishop), the successor to Get-Git. It has a much broader capability for scanning (although you can use the default rulesets and only enable the options for scanning Git repos, which will behave identically to Get-Git), and allows for blacklisting sites through a regex that urls must match to be scanned. You can also adjust scan rate, add custom rules, etc. - just generally a more fully featured extension.
